### PR TITLE
Initial support for custom theming/styling 

### PR DESCRIPTION
**Pull request by nelson-glauber**
This PR adds an initial implementation for theming/styling. In this implementation, the theme is defined in a JSON file located in `priv/static/assets` folder in the LiveView project. This file must be named `android_style.json`. 

In this JSON file, it's possible to customize colors, typography (text style), and shapes. This file has the following structure:
```
{
    "colors": {
        "lightColors": { 
        },
        "darkColors": {   
        },
    },
    "typography": {
    },
    "shapes": {
    }
```
The color names are defined in [Material Specification](https://m3.material.io/styles/color/the-color-system/custom-colors) and must be declared using camelCase style (e.g.: `primary`, `onPrimary`, `primaryContainer`, etc). It's important to define at least the `primary`, `secondary` and `tertiary` colors. The color value is defined in AARRGGBB. 
```
{
    "colors": {
        "lightColors": {
            "primary": "#FFB90063",
            "secondary": "#FF74565F",
            "tertiary": "#FF7C5635",
            ...
```
For typography, it's possible to customize several text params: font family, color, font size, font weight, font style (normal or italic), letter spacing, background color, text decoration (underline or line-through), text align, line height, line break (simple, paragraph and heading), hyphens (none or auto), text direction (RTL, LTR), font feature settings.
The name of each typography item is also following the [Material Design](https://m3.material.io/styles/typography/type-scale-tokens) convention (`displayLarge`, `titleMedium`, `headlineSmall`, etc.)
The font family is obtained by [Downloadable Fonts API](https://developer.android.com/develop/ui/views/text-and-emoji/downloadable-fonts) using [Google Fonts](https://fonts.google.com/) provider. 
```
{
    "typography": {     
        "labelLarge": {
            "fontFamily": "Orbitron",
            "fontWeight": "W500",
            "fontSize": "24",
            "lineHeight": "30",
            "letterSpacing": "0.75"
        },
        ...
```
For [shapes](https://m3.material.io/styles/shape/overview), it's currently supported 3 types: `circle`, `rectangle`,  and an integer value that represents the rounded corner of the shape.
```
{
    "shapes": {
        "small": "4",
        "medium": "rectangle",
        ...
    }
```

Finally, this PR also includes:
- Migration from Material 2 to Material 3
- Removed unnecessary resource files
- Some properties that are common in components and theme were moved to the respective theme file.
- Added a few unimplemented properties in several components.
- Added customization for individual buttons (independent of the app theme)
- Added `clickable` modifier for some components.

### CODE REVIEW

**Comment by bcardarella** [comment]
Just an FYI that we will probably want to change this format to align with what we're doing on SwiftUI at some point. Keeping this as JSON for now is OK.

**Comment by bcardarella** [comment]
@nelson-glauber I'd like to explore if/how to we can align with what we're doing in swiftui client. Can we wait on this merge or moving forward until we've vetted the swiftui modifier solution?

**Comment by nelson-glauber** [comment]
> @nelson-glauber I'd like to explore if/how to we can align with what we're doing in swiftui client. Can we wait on this merge or moving forward until we've vetted the swiftui modifier solution?

Sure @bcardarella. I'm working with Sebastian on the merge/diff integration with Core. I'm using a branch created on top of this one. 
Depending on the changes requested, I think I will just need to do a rebase. Otherwise, it would be better to merge this branch and open an issue to replace the JSON approach for the other one used by SwiftUI.

**Comment by bcardarella** [comment]
@nelson-glauber ok, if you are concerned about the branch going stale and merging later would be a huge lift then you can merge in but let's leave the door open that this code or part of this code can be walked back in the future once we've aligned on the interface for styling

**Review by bcardarella — APPROVED** [review]

**Review by supernintendo — APPROVED** [review]

**Pull request merged**
