### PR TITLE
Add Elixir platform library

### PR DESCRIPTION
**Pull request by supernintendo**
This PR adds all of the essential pieces to make this a proper platform library that can be used with [live_view_native](https://github.com/liveview-native/live_view_native), similar to [liveview-client-swiftui](https://github.com/liveview-native/liveview-client-swiftui).

### CODE REVIEW

**Comment by supernintendo** [comment]
@Kashif-E @KronicDeth I'm running into a blocker with this but not familiar enough with what's going on within the Kotlin side of things to figure it out. `live_view_native` relies on `get_connect_params/1` returning a map with the `_platform` param to determine what type of client a socket is connecting from to be able to know which platform-specific template to use when rendering a LiveView for the session. It appears that `get_connect_params/1` is returning `nil` however, which prevents this. It looks like we're correctly seeing the `_platform` and other connect params [here](channelConnectionParams) but I'm not sure why the Elixir side isn't seeing that:

From live_view_native [here](https://github.com/liveview-native/live_view_native/blob/main/lib/live_view_native/live_session.ex#L9) (note the added comment at the top of `on_mount/4`):

```elixir
defmodule LiveViewNative.LiveSession do
  @moduledoc """
  Ensures common `assigns` are applied to all LiveViews attaching this hook.
  """
  import Phoenix.LiveView
  import Phoenix.Component, only: [assign: 3]

  def on_mount(:live_view_native, _params, _session, socket) do
    # The first line of the `with` statement matches on iOS but not on Android
    # This is due to `get_connect_params/1` returning `nil` for clients connecting from liveview-client-jetpack
    with %{"_platform" => platform_id} <- get_connect_params(socket),
         platforms <- LiveViewNative.platforms(),
         %LiveViewNativePlatform.Context{} = platform_context <- Map.get(platforms, platform_id) do
      {:cont, assign(socket, :native, platform_context)}
    else
      _result ->
        platform_config = %LiveViewNative.Platforms.Web{}
        platform_context = LiveViewNativePlatform.context(platform_config)

        {:cont, assign(socket, :native, platform_context)}
    end
  end
end
```

I created the [android-test](https://github.com/liveview-native/scratchboard/tree/android-test) branch on the scratchboard project if you'd like to test this yourself. Thanks in advance. 🙂

**Comment by Kashif-E** [comment]
I tried investigating this on my machine but i am getting this error @supernintendo 
```
 mix phx.server 
Could not compile :live_view_native_jetpack, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
Error while loading project :decimal at /Users/KashifWork/Desktop/scratchboard/deps/decimal
** (FunctionClauseError) no function clause matching in Keyword.merge/2    
    
    The following arguments were given to Keyword.merge/2:
    
        # 1
        [app: nil, aliases: [], build_embedded: false, build_per_environment: true, build_scm: Mix.SCM.Path, config_path: "config/config.exs", consolidate_protocols: true, default_task: "run", deps: [], deps_path: "deps", elixirc_paths: ["lib"], erlc_paths: ["src"], erlc_include_path: "include", erlc_options: [], lockfile: "mix.lock", preferred_cli_env: [], start_permanent: false]
    
        # 2
        Decimal.Mixfile
    
    Attempted function clauses (showing 3 out of 3):
    
        def merge(keywords1, []) when is_list(keywords1)
        def merge([], keywords2) when is_list(keywords2)
        def merge(keywords1, keywords2) when is_list(keywords1) and is_list(keywords2)
    
    (elixir 1.14.4) lib/keyword.ex:979: Keyword.merge/2
    (mix 1.14.4) lib/mix/project.ex:141: Mix.Project.push/3
    (stdlib 4.3) lists.erl:1350: :lists.foldl/3
```

**Comment by pshoukry** [comment]
@supernintendo and @Kashif-E I think its a bit late for me to help with the swiftUI but I am very interested in helping with Jetpack and be involved ... can you point me to a starting point ? where i can pick a first task?

**Comment by supernintendo** [comment]
It lives! Amazing work @nelson-glauber 😊 

Screenshot 2023-09-21 at 10 54 38 AM

**Review by nelson-glauber — APPROVED** [review]

**Pull request merged**
